// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { insertChatBlock } from '.'
import { auth } from './auth'

export const insertChatBlockSchema = parseBlockSchema(insertChatBlock)
export const insertChatCredentialsSchema = parseBlockCredentials(
  insertChatBlock.id,
  auth.schema
)
