// Do not edit this file manually
import { parseBlockSchema } from '@typebot.io/forge'
import { advancedStyleBlock } from '.'

export const advancedStyleBlockSchema = parseBlockSchema(advancedStyleBlock)
