// Do not edit this file manually
import { parseBlockSchema } from '@typebot.io/forge'
import { advancedMediaBlock } from '.'

export const advancedMediaBlockSchema = parseBlockSchema(advancedMediaBlock)
