// Do not edit this file manually
import { ForgedBlock } from './types'

export const forgedBlockIds = [
  'openai',
  'cal-com',
  'chat-node',
  'qr-code',
  'dify-ai',
  'mistral',
  'elevenlabs',
  'anthropic',
  'together-ai',
  'open-router',
  'nocodb',
  'segment',
  'inworld',
  'advanced-style',
  'openid',
  'groq',
  'insert-chat',
  'convai',
  'zendesk',
] as const satisfies ForgedBlock['type'][]
