// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { inworldBlock } from '.'

export const inworldBlockSchema = parseBlockSchema(inworldBlock)
export const inworldCredentialsSchema = parseBlockCredentials(inworldBlock)
