const LANGUAGES: Array<[string, string]> =
  [
    ["Arabic", "ar"],
    ["Cantonese", "zh-HK"],
    ["Chinese (Hong Kong)", "yue-HK"],
    ["Chinese (Mainland)", "cmn-CN"],
    ["Dutch (Belgium)" ,"nl-BE"],
    ["Dutch" ,"nl-NL"],
    ["English" ,"en-US"],
    ["Finnish" ,"fi-FI"],
    ["French" ,"fr-FR"],
    ["German" ,"de-DE"],
    ["Hindi" ,"hi-IN"],
    ["Italian" ,"it-IT"],
    ["Japanese" ,"js-JP"],
    ["Kazach (Kazakhatan)" ,"kk-KZ"],
    ["Korean" ,"ko-KR"],
    ["Mexican Spanish" ,"es-MX"],
    ["Polish (Poland)" ,"pl-PL"],
    ["Portuguese (Brazil)" ,"pt-BR"],
    ["Portuguese (Portugal)" ,"pt-PT"],
    ["Russian" ,"ru-RU"],
    ["Spanish" ,"es-ES"],
    ["Spanish (United States)" ,"es-US"],
    ["Swedish" ,"sv-SE"],
    ["Turkish" ,"tr-TR"],
    ["Vietnamese" ,"vi-VN"],
  ]

export const VOICES: Array<[string, string, string, string]> = [
["Alien Voice","Convai Voices (New)","CONVAI-CLONED-VOICE-772e4128-5420-4117-93ea-830dd2b6397b","en-US"],
["American Middle-aged Determined Male","Convai Voices (New)","CONVAI-CLONED-VOICE-d9f0f410-e1fa-466f-b89a-d5f4f7eed5d4","en-US"],
["American Middle-aged Husky Female","Convai Voices (New)","CONVAI-CLONED-VOICE-348737a3-0503-4675-b4f4-b4ec4a284df5","en-US"],
["American Old Calm Male","Convai Voices (New)","CONVAI-CLONED-VOICE-730e46d6-1897-48e4-a18f-3851dbb32250","en-US"],
["Indian American Middle Aged Male","Convai Voices (New)","CONVAI-CLONED-VOICE-69d0fbc7-e80a-4946-ac8e-0cf5c2eed143","en-US"],
["Middle Aged Enthusiastic Female","Convai Voices (New)","CONVAI-CLONED-VOICE-dbbe7465-d0da-46d0-ad34-8737fb55d802","en-US"],
["Old Cranky American Male","Convai Voices (New)","CONVAI-CLONED-VOICE-90914143-1bd3-4119-9e70-25ba55c4b762","en-US"],
["Witch Voice","Convai Voices (New)","CONVAI-CLONED-VOICE-02d97263-c289-4f73-ba73-55a3e0cd0852","en-US"],
["Amber Female American English Voice","Azure Voices","AmberNeural","en-US"],
["Ashley Female American English Voice","Azure Voices","AshleyNeural","en-US"],
["Aria Female American English Voice","Azure Voices","AriaNeural","en-US"],
["Brandon Male American English Voice","Azure Voices","BrandonNeural","en-US"],
["Christopher Male American English Voice","Azure Voices","ChristopherNeural","en-US"],
["Cora Female American English Voice","Azure Voices","CoraNeural","en-US"],
["Davis Male American English Voice","Azure Voices","DavisNeural","en-US"],
["Elizabeth Female American English Voice","Azure Voices","ElizabethNeural","en-US"],
["Eric Male American English Voice","Azure Voices","EricNeural","en-US"],
["Female Cantonese Voice","Azure Voices","HiuMaanNeural","zh-HK"],
["Female Cantonese Voice 2","Azure Voices","HiuGaaiNeural","zh-HK"],
["Female Child Voice","Azure Voices","AnaNeural","en-US"],
["Female Kazakh Voice 1","Azure Voices","AigulNeural","kk-KZ"],
["Female Mexican Spanish Voice","Azure Voices","DaliaNeural","es-MX"],
["Female Mexican Spanish Voice 2","Azure Voices","BeatrizNeural","es-MX"],
["Female Mexican Spanish Voice 3","Azure Voices","CandelaNeural","es-MX"],
["Female Mexican Spanish Voice 4","Azure Voices","CarlotaNeural","es-MX"],
["Female Mexican Spanish Voice 5","Azure Voices","LarissaNeural","es-MX"],
["Female Mexican Spanish Voice 6","Azure Voices","MarinaNeural","es-MX"],
["Female Mexican Spanish Voice 7","Azure Voices","NuriaNeural","es-MX"],
["Female Mexican Spanish Voice 8","Azure Voices","RenataNeural","es-MX"],
["Guy Male American English Voice","Azure Voices","GuyNeural","en-US"],
["Harri ( Young Calm Finnish Male )","Azure Voices","FIFIHarriNeural","fi-FI"],
["Jacob Male American English Voice","Azure Voices","JacobNeural","en-US"],
["Jane Female American English Voice","Azure Voices","JaneNeural","en-US"],
["Jason Male American English Voice","Azure Voices","JasonNeural","en-US"],
["Jenny Female American English Voice","Azure Voices","JennyNeural","en-US"],
["JennyMultilingualV2 Female American English Voice","Azure Voices","JennyMultilingualV2Neural","ar-EG,ar-SA,ca-ES,cs-CZ,da-DK,de-AT,de-CH,de-DE,en-AU,en-CA,en-GB,en-HK,en-IE,en-IN,en-US,es-ES,es-MX,fi-FI,fr-BE,fr-CA,fr-CH,fr-FR,hi-IN,hu-HU,id-ID,it-IT,ja-JP,ko-KR,nb-NO,nl-BE,nl-NL,pl-PL,pt-BR,pt-PT,ru-RU,sv-SE,th-TH,tr-TR,zh-CN,zh-HK,zh-TW"],
["Male Cantonese Voice","Azure Voices","WanLungNeural","zh-HK"],
["Male Kazakh Voice 1","Azure Voices","DauletNeural","kk-KZ"],
["Male Mexican Spanish Voice","Azure Voices","JorgeNeural","es-MX"],
["Male Mexican Spanish Voice 2","Azure Voices","CecilioNeural","es-MX"],
["Male Mexican Spanish Voice 3","Azure Voices","GerardoNeural","es-MX"],
["Male Mexican Spanish Voice 4","Azure Voices","LibertoNeural","es-MX"],
["Male Mexican Spanish Voice 5","Azure Voices","LucianoNeural","es-MX"],
["Male Mexican Spanish Voice 6","Azure Voices","PelayoNeural","es-MX"],
["Male Mexican Spanish Voice 7","Azure Voices","YagoNeural","es-MX"],
["Michelle Female American English Voice","Azure Voices","MichelleNeural","en-US"],
["Monica Female American English Voice","Azure Voices","MonicaNeural","en-US"],
["Nancy Female American English Voice","Azure Voices","NancyNeural","en-US"],
["Noora ( Middle Aged Finnish Female )","Azure Voices","FIFINooraNeural","fi-FI"],
["Roger Male American English Voice","Azure Voices","RogerNeural","en-US"],
["RyanMultilingual Male American English Voice","Azure Voices","RyanMultilingualNeural","ar-EG,ar-SA,ca-ES,cs-CZ,da-DK,de-AT,de-CH,de-DE,en-AU,en-CA,en-GB,en-HK,en-IE,en-IN,en-US,es-ES,es-MX,fi-FI,fr-BE,fr-CA,fr-CH,fr-FR,hi-IN,hu-HU,id-ID,it-IT,ja-JP,ko-KR,nb-NO,nl-BE,nl-NL,pl-PL,pt-BR,pt-PT,ru-RU,sv-SE,th-TH,tr-TR,zh-CN,zh-HK,zh-TW"],
["Sara Female American English Voice","Azure Voices","SaraNeural","en-US"],
["Selma ( Young Calm Finnish Female)","Azure Voices","FIFISelmaNeural","fi-FI"],
["Steffan Male American English Voice","Azure Voices","SteffanNeural","en-US"],
["Tony Male American English Voice","Azure Voices","TonyNeural","en-US"],
["High quality US Feminine Voice","Convai Voices","FEMALE","en-US"],
["High quality US Masculine Voice","Convai Voices","MALE","en-US"],
["Adam (Arabic)","Elevenlabs Voices","Adam-ar-MALE","ar"],
["Adam (Chinese)","Elevenlabs Voices","Adam-cmn-CN-MALE","cmn-CN"],
["Adam (Dutch)","Elevenlabs Voices","Adam-nl-NL-MALE","nl-NL"],
["Adam (Japanese)","Elevenlabs Voices","Adam-ja-JP-MALE","ja-JP"],
["Adam (Korean)","Elevenlabs Voices","Adam-ko-KR-MALE","ko-KR"],
["Adam (Middle-aged Wise Brazilian Portuguese Masculine Voice)","Elevenlabs Voices","Adam-pt-BR","pt-BR"],
["Adam (Middle-aged Wise French Masculine Voice)","Elevenlabs Voices","Adam-fr-FR","fr-FR"],
["Adam (Middle-aged Wise German Masculine Voice)","Elevenlabs Voices","Adam-de-DE","de-DE"],
["Adam (Middle-aged Wise Italian Masculine Voice)","Elevenlabs Voices","Adam-it-IT","it-IT"],
["Adam (Middle-aged Wise Polish Masculine Voice)","Elevenlabs Voices","Adam-pl-PL","pl-PL"],
["Adam (Middle-aged Wise Portuguese Masculine Voice)","Elevenlabs Voices","Adam-pt-PT","pt-PT"],
["Adam (Middle-aged Wise Spanish Masculine Voice)","Elevenlabs Voices","Adam-es-ES","es-ES"],
["Adam (Middle-aged Wise US Masculine Voice)","Elevenlabs Voices","Adam-en-US","en-US,fi-FI"],
["Adam (Middle-aged Wise US Spanish Masculine Voice)","Elevenlabs Voices","Adam-es-US","es-US"],
["Adam (Turkish)","Elevenlabs Voices","Adam-tr-TR-MALE","tr-TR"],
["Admiral Davis ( Middle-aged Strong Authoritative Male )","Elevenlabs Voices","ConvaiAdmiralDavis_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI,sk-SK,cs-CZ"],
["Alice (Middle-Aged British Female Voice)","Elevenlabs Voices","11LABS-AUTO-Alice_c8ff047a678dbde796ef781db3df11a2b56aa3b62bdf4c86a3893b64cb02685e","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Antoni (Young Deep Brazilian Portuguese Masculine Voice)","Elevenlabs Voices","Antoni-pt-BR","pt-BR"],
["Antoni (Young Deep French Masculine Voice)","Elevenlabs Voices","Antoni-fr-FR","fr-FR"],
["Antoni (Young Deep German Masculine Voice)","Elevenlabs Voices","Antoni-de-DE","de-DE"],
["Antoni (Young Deep Italian Masculine Voice)","Elevenlabs Voices","Antoni-it-IT","it-IT"],
["Antoni (Young Deep Polish Masculine Voice)","Elevenlabs Voices","Antoni-pl-PL","pl-PL"],
["Antoni (Young Deep Portuguese Masculine Voice)","Elevenlabs Voices","Antoni-pt-PT","pt-PT"],
["Antoni (Young Deep Spanish Masculine Voice)","Elevenlabs Voices","Antoni-es-ES","es-ES"],
["Antoni (Young Deep US Masculine Voice)","Elevenlabs Voices","Antoni-en-US","en-US,fi-FI"],
["Antoni (Young Deep US Spanish Masculine Voice)","Elevenlabs Voices","Antoni-es-US","es-US"],
["Arnold (Middle-aged Brazilian Portuguese Masculine Voice)","Elevenlabs Voices","Arnold-pt-BR","pt-BR"],
["Arnold (Middle-aged French Masculine Voice)","Elevenlabs Voices","Arnold-fr-FR","fr-FR"],
["Arnold (Middle-aged German Masculine Voice)","Elevenlabs Voices","Arnold-de-DE","de-DE"],
["Arnold (Middle-aged Italian Masculine Voice)","Elevenlabs Voices","Arnold-it-IT","it-IT"],
["Arnold (Middle-aged Polish Masculine Voice)","Elevenlabs Voices","Arnold-pl-PL","pl-PL"],
["Arnold (Middle-aged Portuguese Masculine Voice)","Elevenlabs Voices","Arnold-pt-PT","pt-PT"],
["Arnold (Middle-aged Spanish Masculine Voice)","Elevenlabs Voices","Arnold-es-ES","es-ES"],
["Arnold (Middle-aged US Masculine Voice)","Elevenlabs Voices","Arnold-en-US","en-US,fi-FI"],
["Arnold (Middle-aged US Spanish Masculine Voice)","Elevenlabs Voices","Arnold-es-US","es-US"],
["Bella (Young Brazilian Portuguese Feminine Voice)","Elevenlabs Voices","Bella-pt-BR","pt-BR"],
["Bella (Young French Feminine Voice)","Elevenlabs Voices","Bella-fr-FR","fr-FR"],
["Bella (Young German Feminine Voice)","Elevenlabs Voices","Bella-de-DE","de-DE"],
["Bella (Young Italian Feminine Voice)","Elevenlabs Voices","Bella-it-IT","it-IT"],
["Bella (Young Polish Feminine Voice)","Elevenlabs Voices","Bella-pl-PL","pl-PL"],
["Bella (Young Portuguese Feminine Voice)","Elevenlabs Voices","Bella-pt-PT","pt-PT"],
["Bella (Young Spanish Feminine Voice)","Elevenlabs Voices","Bella-es-ES","es-ES"],
["Bella (Young US Feminine Voice)","Elevenlabs Voices","Bella-en-US","en-US,fi-FI"],
["Bella (Young US Spanish Feminine Voice)","Elevenlabs Voices","Bella-es-US","es-US"],
["Bill (Old American Male Voice)","Elevenlabs Voices","11LABS-AUTO-Bill_ce6ff01ff0d44424128f9eeb7917d91abf504c57bf38402760437122ef930fe3","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Bobby ( Young Cute American Female - Young English Child )","Elevenlabs Voices","Bobby - young English child_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Brian (Middle-Aged American Male Voice)","Elevenlabs Voices","11LABS-AUTO-Brian_41ceeceb352c56d5fd945d9050cd44abb712405409bb4cbef67d14140ceba0eb","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Callum ( Middle Aged Hoarse American Male )","Elevenlabs Voices","Callum_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Charlie ( Middle Aged Casual Australian Male )","Elevenlabs Voices","Charlie_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Charlotte ( Middle Aged Seductive English-Swedish Female )","Elevenlabs Voices","Charlotte_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Chris (Middle-Aged American Male Voice)","Elevenlabs Voices","11LABS-AUTO-Chris_588e12dd2f837a5f5404b64477c64fcfa5a69c0862d98444e6f0860675e481a9","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Clyde ( Middle Aged War Veteran American Male )","Elevenlabs Voices","Clyde_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Daniel ( Young Casual American Male )","Elevenlabs Voices","Daniel_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Dave ( Young Conversational British-Essex Male )","Elevenlabs Voices","Dave_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Diego ( Young Mature American Male )","Elevenlabs Voices","Diego v1_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Domi (Young High-pitched Brazilian Portuguese Feminine Voice)","Elevenlabs Voices","Domi-pt-BR","pt-BR"],
["Domi (Young High-pitched French Feminine Voice)","Elevenlabs Voices","Domi-fr-FR","fr-FR"],
["Domi (Young High-pitched German Feminine Voice)","Elevenlabs Voices","Domi-de-DE","de-DE"],
["Domi (Young High-pitched Italian Feminine Voice)","Elevenlabs Voices","Domi-it-IT","it-IT"],
["Domi (Young High-pitched Polish Feminine Voice)","Elevenlabs Voices","Domi-pl-PL","pl-PL"],
["Domi (Young High-pitched Portuguese Feminine Voice)","Elevenlabs Voices","Domi-pt-PT","pt-PT"],
["Domi (Young High-pitched Spanish Feminine Voice)","Elevenlabs Voices","Domi-es-ES","es-ES"],
["Domi (Young High-pitched US Feminine Voice)","Elevenlabs Voices","Domi-en-US","en-US,fi-FI"],
["Domi (Young High-pitched US Spanish Feminine Voice)","Elevenlabs Voices","Domi-es-US","es-US"],
["Dorothy-v2","Elevenlabs Voices","Dorothy-v2-convai-clone","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI,sk-SK,cs-CZ"],
["Dorothy ( Young Pleasant British Female )","Elevenlabs Voices","Dorothy_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Elli (Middle-aged Brazilian Portuguese Feminine Voice)","Elevenlabs Voices","Elli-pt-BR","pt-BR"],
["Elli (Middle-aged French Feminine Voice)","Elevenlabs Voices","Elli-fr-FR","fr-FR"],
["Elli (Middle-aged German Feminine Voice)","Elevenlabs Voices","Elli-de-DE","de-DE"],
["Elli (Middle-aged Italian Feminine Voice)","Elevenlabs Voices","Elli-it-IT","it-IT"],
["Elli (Middle-aged Polish Feminine Voice)","Elevenlabs Voices","Elli-pl-PL","pl-PL"],
["Elli (Middle-aged Portuguese Feminine Voice)","Elevenlabs Voices","Elli-pt-PT","pt-PT"],
["Elli (Middle-aged Spanish Feminine Voice)","Elevenlabs Voices","Elli-es-ES","es-ES"],
["Elli (Middle-aged US Feminine Voice)","Elevenlabs Voices","Elli-en-US","en-US,fi-FI"],
["Elli (Middle-aged US Spanish Feminine Voice)","Elevenlabs Voices","Elli-es-US","es-US"],
["Emily ( Young Calm American Female )","Elevenlabs Voices","Emily_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Eric (Middle-Aged American Male Voice)","Elevenlabs Voices","11LABS-AUTO-Eric_1e0c5d7793b1296cb88ddddf08040c9e901c241640ff7e88fcad1c31c7392bc9","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Ethan ( Young Whisper American Male )","Elevenlabs Voices","Ethan_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Fin ( Old Sailor Irish Male )","Elevenlabs Voices","Fin_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Freya ( Young Overhyped American Female )","Elevenlabs Voices","Freya_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Gigi ( Young Childlish American Female )","Elevenlabs Voices","Gigi_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Giovanni ( Young Foreigner English-Italian Male )","Elevenlabs Voices","Giovanni_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Glinda ( Middle Aged Witch American Female )","Elevenlabs Voices","Glinda_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Grace ( Young Gentle American-Southern Female )","Elevenlabs Voices","Grace_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Harry ( Young Anxious American Male )","Elevenlabs Voices","Harry_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["James ( Old Calm Australian Male )","Elevenlabs Voices","James_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Jeff ( Deep Clear American Male )","Elevenlabs Voices","Jeff Narration 02_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Jeffery ( Deep Clear Southern Accent American Male )","Elevenlabs Voices","Jeff Southern 01_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Jeremy ( Young Excited American-Irish Male )","Elevenlabs Voices","Jeremy_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Jessica (Young American Female Voice)","Elevenlabs Voices","11LABS-AUTO-Jessica_2f2a5e916dff23fe1869185943af889cf45d35a3e57258fcea2b03332a3bd9ab","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Jessie ( Old Raspy American Male )","Elevenlabs Voices","Jessie_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Joseph ( Middle Aged Ground Reporter British Male )","Elevenlabs Voices","Joseph_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Josh (Middle-aged Brazilian Portuguese Masculine Voice)","Elevenlabs Voices","JOSH-pt-BR","pt-BR"],
["Josh (Middle-aged French Masculine Voice)","Elevenlabs Voices","JOSH-fr-FR","fr-FR"],
["Josh (Middle-aged German Masculine Voice)","Elevenlabs Voices","JOSH-de-DE","de-DE"],
["Josh (Middle-aged Italian Masculine Voice)","Elevenlabs Voices","JOSH-it-IT","it-IT"],
["Josh (Middle-aged Polish Masculine Voice)","Elevenlabs Voices","JOSH-pl-PL","pl-PL"],
["Josh (Middle-aged Portuguese Masculine Voice)","Elevenlabs Voices","JOSH-pt-PT","pt-PT"],
["Josh (Middle-aged Spanish Masculine Voice)","Elevenlabs Voices","JOSH-es-ES","es-ES"],
["Josh (Middle-aged US Masculine Voice)","Elevenlabs Voices","JOSH-en-US","en-US,fi-FI"],
["Josh (Middle-aged US Spanish Masculine Voice)","Elevenlabs Voices","JOSH-es-US","es-US"],
["Laura (Young American Female Voice)","Elevenlabs Voices","11LABS-AUTO-Laura_109c4ca3bd6e18cedd3675ed3e690de60b6bd8c00bebd004d3c7305c3c24c6e4","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Liam ( Young Neutral American Male )","Elevenlabs Voices","Liam_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Lily (Middle-Aged British Female Voice)","Elevenlabs Voices","11LABS-AUTO-Lily_41b8b61f0946eb69bc7b83a0da94319d43485ae0644f720d7706e08b8e88a276","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Matilda ( Young Warm American Female )","Elevenlabs Voices","Matilda_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Matthew ( Middle Aged Calm British Male )","Elevenlabs Voices","Matthew_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Michael ( Old Orotund American Male )","Elevenlabs Voices","Michael_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Mimi ( Young Childish English-Swedish Female )","Elevenlabs Voices","Mimi_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Ned - Nerdy Cartoon Sound ( Old Pleasant American Male )","Elevenlabs Voices","Ned - nerdy cartoon sound_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Neil ( Old Husky American Male )","Elevenlabs Voices","Neil_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Nicole ( Young Whisper American Female )","Elevenlabs Voices","Nicole_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Nicoletta ( Young Calm American Female )","Elevenlabs Voices","Nicoletta_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Patrick ( Middle Aged Shouty American Male )","Elevenlabs Voices","Patrick_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Rachel (Young Brazilian Portuguese Feminine Voice)","Elevenlabs Voices","Rachel-pt-BR","pt-BR"],
["Rachel (Young French Feminine Voice)","Elevenlabs Voices","Rachel-fr-FR","fr-FR"],
["Rachel (Young German Feminine Voice)","Elevenlabs Voices","Rachel-de-DE","de-DE"],
["Rachel (Young Italian Feminine Voice)","Elevenlabs Voices","Rachel-it-IT","it-IT"],
["Rachel (Young Polish Feminine Voice)","Elevenlabs Voices","Rachel-pl-PL","pl-PL"],
["Rachel (Young Portuguese Feminine Voice)","Elevenlabs Voices","Rachel-pt-PT","pt-PT"],
["Rachel (Young Spanish Feminine Voice)","Elevenlabs Voices","Rachel-es-ES","es-ES"],
["Rachel (Young US Feminine Voice)","Elevenlabs Voices","Rachel-en-US","en-US,fi-FI"],
["Rachel (Young US Spanish Feminine Voice)","Elevenlabs Voices","Rachel-es-US","es-US"],
["Rafael ( Old Mature American Male - Deep And Clear Voice )","Elevenlabs Voices","Rafael - Deep AND clear Voice_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Rose - Young Clear Soft Speech ( Young Soft American Female )","Elevenlabs Voices","Rose - Young clear soft speech_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Ryan ( Middle Aged Soldier American Male )","Elevenlabs Voices","Ryan_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Sam ( Young Brazilian Portuguese Masculine Voice )","Elevenlabs Voices","Sam-pt-BR","pt-BR"],
["Sam ( Young French Masculine Voice )","Elevenlabs Voices","Sam-fr-FR","fr-FR"],
["Sam ( Young German Masculine Voice )","Elevenlabs Voices","Sam-de-DE","de-DE"],
["Sam ( Young Italian Masculine Voice )","Elevenlabs Voices","Sam-it-IT","it-IT"],
["Sam ( Young Polish Masculine Voice )","Elevenlabs Voices","Sam-pl-PL","pl-PL"],
["Sam ( Young Portuguese Masculine Voice )","Elevenlabs Voices","Sam-pt-PT","pt-PT"],
["Sam ( Young Spanish Masculine Voice )","Elevenlabs Voices","Sam-es-ES","es-ES"],
["Sam ( Young US Masculine Voice )","Elevenlabs Voices","Sam-en-US","en-US,fi-FI"],
["Sam ( Young US Spanish Masculine Voice )","Elevenlabs Voices","Sam-es-US","es-US"],
["Serena ( Young Hyped American Female )","Elevenlabs Voices","Serena_FEMALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Thomas ( Young Calm American Male )","Elevenlabs Voices","Thomas_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Vigo - Young American Male Smooth ( Young Hyped American Male )","Elevenlabs Voices","Vigo - young American male smooth_MALE_11LABS","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Will (Young American Male Voice)","Elevenlabs Voices","11LABS-AUTO-Will_21d370a4c53dd9bbf57129b556361793ec4fb427eb7ff0b8c535f6fdee2bcf9a","en-US,en-GB,en-AU,en-CA,ja-JP,ar,ar-SA,ar-AE,hi-IN,cmn-CN,de-DE,fr-FR,fr-CA,ko-KR,pt-BR,pt-PT,it-IT,es-ES,es-MX,nl-NL,tr-TR,id,fi-FI"],
["Adult Vietnamese Female Voice","GCP Voices","SVIVNFemale 2","vi-VN"],
["Adult Vietnamese Male Voice","GCP Voices","SVIVNMale 2","vi-VN"],
["Calm Arabic Female Voice","GCP Voices","WARXAFemale 2","ar"],
["Calm Arabic Male Voice","GCP Voices","WARXAMale 1","ar"],
["Calm Dutch Accent Female Voice","GCP Voices","WNLNLFemale 32","en-US"],
["Calm Dutch Female Voice","GCP Voices","WNLNLFemale 3","nl-NL"],
["Calm French Accent Male Voice","GCP Voices","WFRFRMale 22","en-US"],
["Calm French Female Voice","GCP Voices","WFRFRFemale 3","fr-FR"],
["Calm French Male Voice","GCP Voices","WFRFRMale 2","fr-FR"],
["Calm German Accent Female Voice","GCP Voices","WDEDEFemale 32","en-US"],
["Calm German Accent Male Voice","GCP Voices","WDEDEMale 32","en-US"],
["Calm German Female Voice","GCP Voices","WDEDEFemale 3","de-DE"],
["Calm German Male Voice","GCP Voices","WDEDEMale 3","de-DE"],
["Calm Japanese Female Voice","GCP Voices","WJAJPFemale 2","ja-JP"],
["Calm Japanese Male Voice","GCP Voices","WJAJPMale 2","ja-JP"],
["Calm Russian Female Voice","GCP Voices","WRURUFemale 3","ru-RU"],
["Calm US Feminine Voice","GCP Voices","WUFemale 1","en-US"],
["Deep US Masculine Voice","GCP Voices","WUMale 4","en-US"],
["Ductch (Belgium) Female Voice","GCP Voices","WNLBEFemale 1","nl-BE"],
["Ductch (Belgium) Male Voice","GCP Voices","WNLBEMale 1","nl-BE"],
["Flat UK Feminine Voice","GCP Voices","WUKFemale 1","en-US"],
["Flat US Feminine Voice","GCP Voices","WUFemale 4","en-US"],
["Heavy Indian Accent Feminine Voice","GCP Voices","WIFemale 22","en-US"],
["Heavy Indian Accent Masculine Voice","GCP Voices","WIMale 22","en-US"],
["Heavy Indian Feminine Voice","GCP Voices","WIFemale 2","hi-IN"],
["Heavy Indian Masculine Voice","GCP Voices","WIMale 2","hi-IN"],
["Heavy UK Feminine Voice","GCP Voices","WUKFemale 2","en-US"],
["Heavy US Masculine Voice","GCP Voices","WUMale 5","en-US"],
["Middle-aged Australian Masculine Voice","GCP Voices","WAMale 2","en-US"],
["Middle-aged Chinese Accent Female Voice","GCP Voices","WCMNCNFemale 22","en-US"],
["Middle-aged Chinese Female Voice","GCP Voices","WCMNCNFemale 2","cmn-CN"],
["Middle-aged Chinese Male Voice","GCP Voices","WCMNCNMale 2","cmn-CN"],
["Middle-aged Dutch Accent Male Voice","GCP Voices","WNLNLMale 22","en-US"],
["Middle-aged Dutch Female Voice","GCP Voices","WNLNLFemale 2","nl-NL"],
["Middle-aged Dutch Male Voice","GCP Voices","WNLNLMale 2","nl-NL"],
["Middle-aged French Accent Female Voice","GCP Voices","WFRFRFemale 22","en-US"],
["Middle-aged French Female Voice","GCP Voices","WFRFRFemale 2","fr-FR"],
["Middle-aged German Female Voice","GCP Voices","WDEDEFemale 2","de-DE"],
["Middle-aged German Male Voice","GCP Voices","WDEDEMale 2","de-DE"],
["Middle-aged Italian Female Voice 2","GCP Voices","SITITFemale 1","it-IT"],
["Middle-aged Italian Female Voice 3","GCP Voices","SITITFemale 2","it-IT"],
["Middle-aged Italian Female Voice 4","GCP Voices","WITITFemale 1","it-IT"],
["Middle-aged Italian Female Voice 5","GCP Voices","WITITFemale 2","it-IT"],
["Middle-aged Italian Male Voice 2","GCP Voices","SITITMale 2","it-IT"],
["Middle-aged Italian Male Voice 3","GCP Voices","WITITMale 1","it-IT"],
["Middle-aged Italian Male Voice 4","GCP Voices","WITITMale 2","it-IT"],
["Middle-aged Korean Female Voice","GCP Voices","WKOKRFemale 2","ko-KR"],
["Middle-aged Korean Male Voice","GCP Voices","WKOKRMale 2","ko-KR"],
["Middle-aged Portuguese (Brazil) Female Voice","GCP Voices","NPTBRFemale 1","pt-BR"],
["Middle-aged Portuguese (Brazil) Female Voice 2","GCP Voices","WPTBRFemale 1","pt-BR"],
["Middle-aged Portuguese (Brazil) Female Voice 3","GCP Voices","WPTBRFemale 2","pt-BR"],
["Middle-aged Portuguese (Brazil) Male Voice 2","GCP Voices","WPTBRMale 1","pt-BR"],
["Middle-aged Russian Accent Female Voice","GCP Voices","WRURUFemale 22","en-US"],
["Middle-aged Russian Accent Male Voice","GCP Voices","WRURUMale 22","en-US"],
["Middle-aged Russian Female Voice","GCP Voices","WRURUFemale 2","ru-RU"],
["Middle-aged Russian Male Voice","GCP Voices","WRURUMale 2","ru-RU"],
["Middle-aged Spanish Female Voice","GCP Voices","WESFemale 1","es-ES"],
["Middle-aged Swedish Female Voice","GCP Voices","SSVSEFemale 1","sv-SE"],
["Middle-aged Swedish Male Voice","GCP Voices","SSVSEMale 2","sv-SE"],
["Middle-aged Turkish Female Voice","GCP Voices","STRTRFemale 1","tr-TR"],
["Middle-aged Turkish Female Voice 2","GCP Voices","WTRTRFemale 3","tr-TR"],
["Middle-aged Turkish Heavy Male Voice","GCP Voices","WTRTRMale 2","tr-TR"],
["Middle-aged Turkish Male Voice","GCP Voices","STRTRMale 1","tr-TR"],
["Middle-aged UK Masculine Voice","GCP Voices","WUKMale 2","en-US"],
["Middle-aged US Feminine Voice","GCP Voices","WUFemale 2","en-US"],
["Middle-aged US Masculine Voice","GCP Voices","WUMale 2","en-US"],
["Middle-aged Vietnamese Female Voice","GCP Voices","NVIVNFemale 1","vi-VN"],
["Middle-aged Vietnamese Female Voice 2","GCP Voices","WVIVNFemale 1","vi-VN"],
["Middle-aged Vietnamese Female Voice 3","GCP Voices","WVIVNFemale 2","vi-VN"],
["Middle-aged Vietnamese Male Voice 2","GCP Voices","WVIVNMale 1","vi-VN"],
["Middle-aged Vietnamese Strong Male Voice","GCP Voices","WVIVNMale 2","vi-VN"],
["Midlle-aged Australian Feminine Voice","GCP Voices","WAFemale 1","en-US"],
["Old Swedish Female Voice","GCP Voices","SSVSEFemale 2","sv-SE"],
["Professional Turkish Female Voice","GCP Voices","STRTRFemale 3","tr-TR"],
["Professional Turkish Male Voice","GCP Voices","STRTRMale 2","tr-TR"],
["Robotic US Masculine Voice","GCP Voices","WUMale 1","en-US"],
["Sharp US Feminine Voice","GCP Voices","WUFemale 5","en-US"],
["Young Arabic Accent Female Voice","GCP Voices","WARXAFemale 12","en-US"],
["Young Arabic Female Voice","GCP Voices","WARXAFemale 1","ar"],
["Young Arabic Male Voice","GCP Voices","WARXAMale 2","ar"],
["Young Australian Feminine Voice","GCP Voices","WAFemale 2","en-US"],
["Young Australian Masculine Voice","GCP Voices","WAMale 1","en-US"],
["Young Chinese Accent Female Voice","GCP Voices","WCMNCNFemale 12","en-US"],
["Young Chinese Accent Male Voice","GCP Voices","WCMNCNMale 12","en-US"],
["Young Chinese Female Voice","GCP Voices","WCMNCNFemale 1","cmn-CN"],
["Young Chinese Male Voice","GCP Voices","WCMNCNMale 1","cmn-CN"],
["Young Dutch Female Voice","GCP Voices","WNLNLFemale 1","nl-NL"],
["Young Dutch Male Voice","GCP Voices","WNLNLMale 1","nl-NL"],
["Young Female Finnish Voice 1","GCP Voices","SFIFIFemale_1","fi-FI"],
["Young Female Finnish Voice 2","GCP Voices","WFIFIFemale_2","fi-FI"],
["Young French Accent Female Voice","GCP Voices","WFRFRFemale 12","en-US"],
["Young French Female Voice","GCP Voices","WFRFRFemale 1","fr-FR"],
["Young French Male Voice","GCP Voices","WFRFRMale 1","fr-FR"],
["Young German Accent Female Voice","GCP Voices","WDEDEFemale 12","en-US"],
["Young German Accent Male Voice","GCP Voices","WDEDEMale 12","en-US"],
["Young German Female Voice","GCP Voices","WDEDEFemale 1","de-DE"],
["Young German Male Voice","GCP Voices","WDEDEMale 1","de-DE"],
["Young Indian Accent Feminine Voice","GCP Voices","WIFemale 12","en-US"],
["Young Indian Accent Masculine Voice","GCP Voices","WIMale 12","en-US"],
["Young Indian Feminine Voice","GCP Voices","WIFemale 1","hi-IN"],
["Young Indian Masculine Voice","GCP Voices","WIMale 1","hi-IN"],
["Young Italian Male Voice","GCP Voices","SITITMale 1","it-IT"],
["Young Japanese Accent Female Voice","GCP Voices","WJAJPFemale 12","en-US"],
["Young Japanese Female Voice","GCP Voices","WJAJPFemale 1","ja-JP"],
["Young Japanese Male Voice","GCP Voices","WJAJPMale 1","ja-JP"],
["Young Korean Accent Female Voice","GCP Voices","WKOKRFemale 12","en-US"],
["Young Korean Female Voice","GCP Voices","WKOKRFemale 1","ko-KR"],
["Young Korean Male Voice","GCP Voices","WKOKRMale 1","ko-KR"],
["Young Portuguese (Brazil) Female Voice 2","GCP Voices","SPTBRFemale 1","pt-BR"],
["Young Portuguese (Brazil) Female Voice 3","GCP Voices","SPTBRFemale 2","pt-BR"],
["Young Portuguese (Brazil) Male Voice","GCP Voices","SPTBRMale 1","pt-BR"],
["Young Russian Female Voice","GCP Voices","WRURUFemale 1","ru-RU"],
["Young Russian Male Voice","GCP Voices","WRURUMale 1","ru-RU"],
["Young Spanish Accent Female Voice","GCP Voices","WESFemale 22","en-US"],
["Young Spanish Accent Male Voice","GCP Voices","WESMale 12","en-US"],
["Young Spanish Female Voice","GCP Voices","WESFemale 2","es-ES"],
["Young Spanish Male Voice","GCP Voices","WESMale 1","es-ES"],
["Young Swedish Female Voice","GCP Voices","SSVSEFemale 3","sv-SE"],
["Young Swedish Male Voice","GCP Voices","SSVSEMale 1","sv-SE"],
["Young Turkish Female Voice","GCP Voices","STRTRFemale 2","tr-TR"],
["Young Turkish Female Voice 2","GCP Voices","WTRTRFemale 1","tr-TR"],
["Young Turkish Female Voice 3","GCP Voices","WTRTRFemale 2","tr-TR"],
["Young Turkish Male Voice","GCP Voices","WTRTRMale 1","tr-TR"],
["Young UK Feminine Voice","GCP Voices","WUKFemale 3","en-US"],
["Young UK Masculine Voice","GCP Voices","WUKMale 1","en-US"],
["Young US Feminine Voice","GCP Voices","WUFemale 3","en-US"],
["Young US Masculine Voice","GCP Voices","WUMale 3","en-US"],
["Young Vietnamese Female Voice","GCP Voices","SVIVNFemale 1","vi-VN"],
["Young Vietnamese Male Voice","GCP Voices","SVIVNMale 1","vi-VN"],
["Alloy (Heavy Feminine voice)","Open AI voices","alloy_OpenAi_341dadca-3911-4880-911d-8b851dde55f0","ar,nl-NL,en-US,fr-FR,de-DE,hi-IN,it-IT,ko-KR,pl-PL,pt-BR,es-ES,ja-JP,id,fi-FI,cs-CZ,sk-SK,iw-IL,ca-ES"],
["Echo (Young Masculine US voice)","Open AI voices","echo_OpenAi_dfdc4a10-f3dc-4c33-84ce-9445f14954e2","ar,nl-NL,en-US,fr-FR,de-DE,hi-IN,it-IT,ko-KR,pl-PL,pt-BR,es-ES,ja-JP,id,fi-FI,cs-CZ,sk-SK,iw-IL,ca-ES"],
["Fable (Young Feminine voice)","Open AI voices","fable_OpenAi_c4d30a32-bcaf-4048-b7b0-0f2bb293205a","ar,nl-NL,en-US,fr-FR,de-DE,hi-IN,it-IT,ko-KR,pl-PL,pt-BR,es-ES,ja-JP,id,fi-FI,cs-CZ,sk-SK,iw-IL,ca-ES"],
["NOVA (Middle-aged Feminine Deep voice)","Open AI voices","nova_OpenAi_6e60e2e7-4fb4-4d62-8461-5b7dae2efee1","ar,nl-NL,en-US,fr-FR,de-DE,hi-IN,it-IT,ko-KR,pl-PL,pt-BR,es-ES,ja-JP,id,fi-FI,cs-CZ,sk-SK,iw-IL,ca-ES"],
["Onyx (Deep Young Masculine voice)","Open AI voices","onyx_OpenAi_1f623a67-ac32-4996-bbea-639560be5d65","ar,nl-NL,en-US,fr-FR,de-DE,hi-IN,it-IT,ko-KR,pl-PL,pt-BR,es-ES,ja-JP,id,fi-FI,cs-CZ,sk-SK,iw-IL,ca-ES"],
["Shimmer (Young adult Feminine Deep voice)","Open AI voices","shimmer_OpenAi_f0c06dd4-a214-4981-a19b-8cc19dea335a","ar,nl-NL,en-US,fr-FR,de-DE,hi-IN,it-IT,ko-KR,pl-PL,pt-BR,es-ES,ja-JP,id,fi-FI,cs-CZ,sk-SK,iw-IL,ca-ES"],
]

export const LANGUAGE_CODES: Array<string> = LANGUAGES.map((l) => (l[1]))
export const LANGUAGE_MAP: Record<string, string>  = LANGUAGES.reduce((acc, l) => {
  acc[l[1]] = l[0]
  return acc
}, {} as Record<string, string>)

export const VOICE_MAP: Record<string, string> = VOICES.reduce((acc, l) => {
  acc[l[2]] = l[0]
  return acc
}, {} as Record<string, string>)

export const VOICE_LANGUAGE_MAP: Record<string, Array<string>> = VOICES.reduce((acc, l) => {
  const langs = l[3].split(",")
  langs.forEach((lang) => {
    acc[lang] ||= []
    acc[lang].push(l[2])
  })
  return acc
}, {} as Record<string, Array<string>>)
