// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { convaiBlock } from '.'
import { auth } from './auth'

export const convaiBlockSchema = parseBlockSchema(convaiBlock)
export const convaiCredentialsSchema = parseBlockCredentials(
  convaiBlock.id,
  auth.schema
)
